### ISSUE TITLE
Accessibility improvement in example

### ISSUE THREAD

**Issue by Mottokrosh** [nguyenj/vue-priority-plus-navigation#1]
Hi,

First off, this is a very cool component, thanks for creating it!

I would only suggest improving the example in the README a little, and stick to the semantically correct `a` tag instead of clickable `span`s:

Where you write:

`<span @click='clickItem(item)'>{{ item.label }}</span>`

I would instead write:

`<a :href="item.link" @click='clickItem(item, $event)'>{{ item.label }}</a>`

(And add a `link` property to the items.) That way you can still handle the clicks in the function if you need special functionality, but a screen reader (or other automated tool) will correctly identify the items as actual links.

**Comment by nguyenj** [comment]
@Mottokrosh thanks for the feedback! I've updated the readme to be more semantically correct.
