### ISSUE TITLE
Uncaught ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by brendon** [nguyenj/vue-priority-plus-navigation#7]
Hi @nguyenj, just wondering if there's anything else special I need to do to get this package working with VueCLI? I'm getting the following error which seems to indicate problems with babel:

```
Uncaught ReferenceError: regeneratorRuntime is not defined
    at eval (priority-plus-navigation.js?0ac6:75)
```

**Comment by brendon** [comment]
This post (https://risanb.com/posts/regenerator-runtime-is-not-defined/) seems to indicate adding:

```
"useBuiltIns": "usage"
```

to the `.babelrc` file (see the end of the article).

**Comment by nguyenj** [comment]
@brendon are you doing any sort of dynamic import or using `async/await`?

**Comment by brendon** [comment]
I was just using VueCLI 3. I wasn't using `async/await` in my other code, but I found that when I took your .vue file and just put it in my project it did work as-is. I think the issue is in the way babel is told not to bother touching files in `node_modules` vs actual application code. The `usage` option will bring in the appropriate polyfill when babel encounters it:

https://babeljs.io/docs/en/babel-preset-env#usebuiltins-usage

At least that's my hunch. 

In the end I took things further because I found a few bugs and just ended up fixing them in my copy.

I am happy to feed them back if you'd like, but the first step would be to get your package working in my app in the first place :D

**Comment by nguyenj** [comment]
PRs are welcomed, so if you would like to contribute I'm more than happy to take a look.

As for the .babelrc issue, you shouldn't be seeing this issue since it's not available in the package. The npm package should only have:

```
vue-priority-plus-navigation
├── LICENSE
├── README.md
├── package.json
├── dist
│   ├── priority-plus-navigation.js
│   └── priority-plus-navigation.js.map
└── src
    └── priority-plus-navigation.vue
```

**Comment by nguyenj** [comment]
@brendon Sorry I understand the issue now. The `regeneratorRuntime` should be resolved now.

**Comment by brendon** [comment]
Thanks @nguyenj, I'll have another go at using this and if successful I'll do up a PR with my fixes. :)

**Comment by brendon** [comment]
See: #8
